import type { DeployConfig } from "../config/types.js";

interface ServiceRoute {
  subdomain: string;
  target: string;
}

/**
 * Generate a Caddyfile for reverse-proxying all Mediabox services
 * with automatic HTTPS via Let's Encrypt.
 */
export function generateCaddyfile(config: DeployConfig): string {
  const { deployment, services } = config;
  if (!deployment.baseDomain || !deployment.letsEncryptEmail) {
    throw new Error(
      "Caddyfile generation requires deployment.baseDomain and deployment.letsEncryptEmail",
    );
  }

  const domain = deployment.baseDomain;
  const email = deployment.letsEncryptEmail;

  const routes: ServiceRoute[] = [
    { subdomain: "jellyfin", target: "jellyfin:8096" },
    { subdomain: "sonarr", target: "sonarr:8989" },
    { subdomain: "radarr", target: "radarr:7878" },
    { subdomain: "prowlarr", target: "prowlarr:9696" },
    { subdomain: "qbit", target: "qbittorrent:8085" },
    { subdomain: "pyload", target: "pyload:8000" },
  ];

  if (services.bazarr.enabled) {
    routes.push({ subdomain: "bazarr", target: "bazarr:6767" });
  }

  const blocks = routes.map(
    (r) => `${r.subdomain}.${domain} {\n  reverse_proxy ${r.target}\n}`,
  );

  // MCP server at the root domain
  blocks.unshift(`${domain} {\n  reverse_proxy mcp-server:3000\n}`);

  const lines = [
    "# =============================================================================",
    "# Mediabox MCP — Caddyfile",
    "# Generated by @mediabox/core",
    "# Automatic HTTPS via Let's Encrypt",
    "# =============================================================================",
    "",
    "{",
    `  email ${email}`,
    "}",
    "",
    ...blocks,
    "",
  ];

  return lines.join("\n");
}
