import type { DeployConfig } from "../config/types.js";
import { toPosix } from "../utils/paths.js";

/**
 * Discovered API keys that can be injected after services are up.
 */
export interface DiscoveredKeys {
  jellyfinApiKey?: string;
  sonarrApiKey?: string;
  radarrApiKey?: string;
  prowlarrApiKey?: string;
}

/**
 * Generate a .env file from DeployConfig. Any API keys that have not yet
 * been discovered are emitted as empty assignments — the setup flow later
 * overwrites them via `updateEnvKeys`.
 */
export function generateEnv(config: DeployConfig, keys?: DiscoveredKeys): string {
  const { deployment, system, paths, services, mcp, ai, telegram } = config;
  // The AI assistant and the Telegram bot share an LLM provider in practice
  // (the wizard collects one set of credentials and feeds both). The
  // canonical source is `config.ai`; we fall back to `telegram.llm` for
  // older callers that still populate the LLM only inside Telegram. Either
  // way we end up with one effective LLM config that drives the env vars.
  const effectiveLlm = ai ?? telegram?.llm;

  const lines: string[] = [
    "# =============================================================================",
    "# Mediabox MCP — Environment Configuration",
    "# Generated by @mediabox/core",
    "# =============================================================================",
    "",
    `DEPLOYMENT_MODE=${deployment.mode}`,
    ...(deployment.baseDomain ? [`BASE_DOMAIN=${deployment.baseDomain}`] : []),
    "",
    "# Host parameters (PR 3.4a edits these via Settings → System)",
    `TZ=${system.timezone}`,
    `PUID=${system.puid}`,
    `PGID=${system.pgid}`,
    "",
    "# Media paths (PR 3.4a edits these via Settings → Media paths)",
    // Docker Compose requires POSIX-style paths even on Windows; toPosix
    // converts backslashes so ${MOVIES_PATH} etc. interpolate correctly
    // into bind-mount sources at compose-up time.
    `MOVIES_PATH=${toPosix(paths.movies)}`,
    `TV_PATH=${toPosix(paths.tv)}`,
    `ANIME_PATH=${toPosix(paths.anime)}`,
    `MUSIC_PATH=${toPosix(paths.music)}`,
    "",
    "# Service Credentials & API Keys (auto-populated by setup wizard)",
    `JELLYFIN_ADMIN_USER=${services.jellyfin.adminUsername}`,
    `JELLYFIN_API_KEY=${keys?.jellyfinApiKey ?? ""}`,
    `SONARR_API_KEY=${keys?.sonarrApiKey ?? ""}`,
    `RADARR_API_KEY=${keys?.radarrApiKey ?? ""}`,
    `QBIT_PASSWORD=${services.qbittorrent.password}`,
    // PyLoad-ng's lscr image creates a single hardcoded account on first
    // run: pyload:pyload. Username can't be changed via the image's env
    // vars or our deploy-time API calls, so we pin it to the default.
    // The password starts as the default and the configure:pyload step
    // rotates it to the wizard's value after the container is healthy
    // (rewriting this line in the same .env once the rotation succeeds).
    `PYLOAD_USER=pyload`,
    `PYLOAD_PASSWORD=pyload`,
    "",
    "# MCP Server",
    `MCP_PUBLIC_URL=${mcp.publicUrl}`,
    `INTERNAL_API_KEY=${mcp.internalApiKey}`,
    `IMAGE_TAG=${deployment.imageTag}`,
  ];

  if (deployment.tunnelToken) {
    lines.push(
      "",
      "# Cloudflare Tunnel",
      `CLOUDFLARE_TUNNEL_TOKEN=${deployment.tunnelToken}`,
    );
  }

  // LLM provider — written whenever the user picks a non-`none` provider
  // in the wizard, regardless of whether they enabled the Telegram bot.
  // Without this, the in-app AI assistant stayed silent on first launch
  // because nothing wrote `LLM_PROVIDER` etc. to .env, even though the
  // user had filled in the AI step. (Settings → AI assistant patches the
  // same vars after the fact, which is why re-entering creds there
  // "fixed" it before this change.)
  if (effectiveLlm) {
    lines.push(
      "",
      "# AI assistant (LLM provider)",
      `LLM_PROVIDER=${effectiveLlm.kind}`,
    );
    if (effectiveLlm.kind === "openrouter") {
      lines.push(
        `OPENROUTER_API_KEY=${effectiveLlm.apiKey}`,
        `LLM_MODEL=${effectiveLlm.model}`,
      );
    } else if (effectiveLlm.kind === "google") {
      lines.push(`GOOGLE_AI_API_KEY=${effectiveLlm.apiKey}`);
      if (effectiveLlm.model) {
        lines.push(`LLM_MODEL=${effectiveLlm.model}`);
      }
    }
  }

  if (telegram) {
    lines.push(
      "",
      "# Telegram Bot",
      `TELEGRAM_BOT_TOKEN=${telegram.botToken}`,
      `ALLOWED_TELEGRAM_USERS=${telegram.allowedUserIds.join(",")}`,
    );
  }

  lines.push(""); // trailing newline
  return lines.join("\n");
}

/**
 * Update specific keys in an existing .env file content.
 * Idempotent: replaces in place if key exists, appends otherwise.
 */
export function updateEnvKeys(envContent: string, updates: Record<string, string>): string {
  let result = envContent;
  for (const [key, value] of Object.entries(updates)) {
    const regex = new RegExp(`^${key}=.*$`, "m");
    if (regex.test(result)) {
      result = result.replace(regex, `${key}=${value}`);
    } else {
      result += `\n${key}=${value}`;
    }
  }
  return result;
}
