import type { DeployConfig } from "../config/types.js";

/**
 * Discovered API keys that can be injected after services are up.
 */
export interface DiscoveredKeys {
  jellyfinApiKey?: string;
  sonarrApiKey?: string;
  radarrApiKey?: string;
  prowlarrApiKey?: string;
}

/**
 * Generate a .env file from DeployConfig. Any API keys that have not yet
 * been discovered are emitted as empty assignments — the setup flow later
 * overwrites them via `updateEnvKeys`.
 */
export function generateEnv(config: DeployConfig, keys?: DiscoveredKeys): string {
  const { deployment, system, services, mcp, telegram } = config;

  const lines: string[] = [
    "# =============================================================================",
    "# Mediabox MCP — Environment Configuration",
    "# Generated by @mediabox/core",
    "# =============================================================================",
    "",
    `DEPLOYMENT_MODE=${deployment.mode}`,
    ...(deployment.baseDomain ? [`BASE_DOMAIN=${deployment.baseDomain}`] : []),
    "",
    `TZ=${system.timezone}`,
    "",
    "# Service Credentials & API Keys (auto-populated by setup wizard)",
    `JELLYFIN_ADMIN_USER=${services.jellyfin.adminUsername}`,
    `JELLYFIN_API_KEY=${keys?.jellyfinApiKey ?? ""}`,
    `SONARR_API_KEY=${keys?.sonarrApiKey ?? ""}`,
    `RADARR_API_KEY=${keys?.radarrApiKey ?? ""}`,
    `QBIT_PASSWORD=${services.qbittorrent.password}`,
    // PyLoad-ng's lscr image creates a single hardcoded account on first
    // run: pyload:pyload. Username can't be changed via the image's env
    // vars or our deploy-time API calls, so we pin it to the default.
    // The password starts as the default and the configure:pyload step
    // rotates it to the wizard's value after the container is healthy
    // (rewriting this line in the same .env once the rotation succeeds).
    `PYLOAD_USER=pyload`,
    `PYLOAD_PASSWORD=pyload`,
    "",
    "# MCP Server",
    `MCP_PUBLIC_URL=${mcp.publicUrl}`,
    `INTERNAL_API_KEY=${mcp.internalApiKey}`,
    `IMAGE_TAG=${deployment.imageTag}`,
  ];

  if (deployment.tunnelToken) {
    lines.push(
      "",
      "# Cloudflare Tunnel",
      `CLOUDFLARE_TUNNEL_TOKEN=${deployment.tunnelToken}`,
    );
  }

  if (telegram) {
    lines.push(
      "",
      "# Telegram Bot",
      `TELEGRAM_BOT_TOKEN=${telegram.botToken}`,
      `LLM_PROVIDER=${telegram.llm.kind}`,
    );
    if (telegram.llm.kind === "openrouter") {
      lines.push(
        `OPENROUTER_API_KEY=${telegram.llm.apiKey}`,
        `LLM_MODEL=${telegram.llm.model}`,
      );
    } else if (telegram.llm.kind === "google") {
      lines.push(`GOOGLE_AI_API_KEY=${telegram.llm.apiKey}`);
      if (telegram.llm.model) {
        lines.push(`LLM_MODEL=${telegram.llm.model}`);
      }
    }
    lines.push(
      `ALLOWED_TELEGRAM_USERS=${telegram.allowedUserIds.join(",")}`,
    );
  }

  lines.push(""); // trailing newline
  return lines.join("\n");
}

/**
 * Update specific keys in an existing .env file content.
 * Idempotent: replaces in place if key exists, appends otherwise.
 */
export function updateEnvKeys(envContent: string, updates: Record<string, string>): string {
  let result = envContent;
  for (const [key, value] of Object.entries(updates)) {
    const regex = new RegExp(`^${key}=.*$`, "m");
    if (regex.test(result)) {
      result = result.replace(regex, `${key}=${value}`);
    } else {
      result += `\n${key}=${value}`;
    }
  }
  return result;
}
