/* ─── 8 virtual tools presented to the LLM ──────────────────────────────────
 * Mirrors exactly what the Telegram bot exposes. Each virtual tool wraps
 * one or more real MCP tools under a single action-based interface,
 * keeping the LLM's tool surface small and semantically clear.
 * ──────────────────────────────────────────────────────────────────────── */
import type { VirtualToolDef } from './types.js';

export const VIRTUAL_TOOLS: Record<string, VirtualToolDef> = {
  server_info: {
    name: 'server_info',
    description: "Server status and activity log. action:'status' for full overview (disk, libraries, sessions, users). action:'activity' for recent playback history.",
    parameters: {
      type: 'object',
      properties: {
        action: { type: 'string', enum: ['status', 'activity'], description: 'status=full overview, activity=who watched what' },
        limit:  { type: 'number', description: 'Entries for activity log (default 15)' },
      },
      required: ['action'],
    },
  },

  media_query: {
    name: 'media_query',
    description: "Search or list Jellyfin content, or get details of a specific item. action:'search' to find/list media (omit query to list all, use page/pageSize to paginate). action:'details' for seasons/episodes of a series (use seasonNumber to filter one season, page/pageSize to paginate episodes).",
    parameters: {
      type: 'object',
      properties: {
        action:       { type: 'string', enum: ['search', 'details'] },
        query:        { type: 'string', description: 'Search term (omit to list all)' },
        type:         { type: 'string', enum: ['Movie', 'Series', 'Episode', 'Audio'] },
        showId:       { type: 'string', description: 'Jellyfin item ID (for details)' },
        seasonNumber: { type: 'number', description: 'Filter details to this season only (recommended for large series)' },
        page:         { type: 'number', description: 'Page number for pagination (default 1)' },
        pageSize:     { type: 'number', description: 'Items per page for pagination (default 50)' },
      },
      required: ['action'],
    },
  },

  library_ops: {
    name: 'library_ops',
    description: 'Manage files and libraries. scan=refresh Jellyfin. create=new library. move=move files/folders. delete=cross-layer delete (Jellyfin+Sonarr/Radarr+disk). list=browse files. rename=standardize episode names. refresh=refresh metadata.',
    parameters: {
      type: 'object',
      properties: {
        action:       { type: 'string', enum: ['scan', 'create', 'move', 'delete', 'list', 'rename', 'refresh'] },
        path:         { type: 'string', description: "File path. 'downloads/' prefix for download folder" },
        sourcePaths:  { type: 'array', items: { type: 'string' }, description: 'Paths to move' },
        destFolder:   { type: 'string', description: 'Move destination' },
        jellyfinItemId: { type: 'string', description: 'Item to delete' },
        name:         { type: 'string', description: 'Library name (create)' },
        libraryType:  { type: 'string', enum: ['movies', 'tvshows', 'music', 'mixed'] },
        folder:       { type: 'string', description: 'Library folder (create)' },
        showPath:     { type: 'string' },
        showName:     { type: 'string' },
        seasonNumber: { type: 'number' },
        dryRun:       { type: 'boolean' },
        itemId:       { type: 'string', description: 'For metadata refresh' },
      },
      required: ['action'],
    },
  },

  series: {
    name: 'series',
    description: "Manage TV series via Sonarr. search=find by name. add=add to monitoring (needs addTvdbId from search, searchNow=false to skip auto-download). status=view series/episodes/calendar/missing/queue/history (use view='episodes' with seriesId to list episodes). remove=delete from Sonarr. releases=find torrents (pass seriesId+seasonNumber+episodeNumber). grab=download specific release.",
    parameters: {
      type: 'object',
      properties: {
        action:        { type: 'string', enum: ['search', 'add', 'status', 'remove', 'releases', 'grab'] },
        query:         { type: 'string' },
        addTvdbId:     { type: 'number' },
        rootFolder:    { type: 'string', enum: ['/tv', '/anime'] },
        monitor:       { type: 'string', enum: ['all', 'future', 'missing', 'none', 'firstSeason', 'lastSeason'] },
        seasons:       { type: 'array', items: { type: 'number' } },
        quality:       { type: 'string', enum: ['Any', 'SD', 'HD-720p', 'HD-1080p', 'Ultra-HD', 'HD - 720p/1080p'] },
        searchNow:     { type: 'boolean', description: 'false=add without downloading (default). true=auto-search.' },
        view:          { type: 'string', enum: ['series', 'episodes', 'calendar', 'missing', 'queue', 'history'] },
        seriesId:      { type: 'number', description: 'Sonarr series ID or tvdbId (auto-resolved)' },
        seasonNumber:  { type: 'number' },
        episodeNumber: { type: 'number', description: 'Episode number (for releases/grab)' },
        page:          { type: 'number', description: 'Page number for episodes/series view (default 1)' },
        pageSize:      { type: 'number', description: 'Items per page for episodes/series view (default 50)' },
        episodeId:     { type: 'number' },
        guid:          { type: 'string' },
        indexerId:     { type: 'number' },
        deleteFiles:   { type: 'boolean' },
        limit:         { type: 'number' },
      },
      required: ['action'],
    },
  },

  movies: {
    name: 'movies',
    description: 'Manage movies via Radarr. search=find by name. add=add to monitoring (needs addTmdbId from search). status=view movies/queue/history. remove=delete from Radarr. releases=find available torrents. grab=download specific release.',
    parameters: {
      type: 'object',
      properties: {
        action:      { type: 'string', enum: ['search', 'add', 'status', 'remove', 'releases', 'grab'] },
        query:       { type: 'string' },
        addTmdbId:   { type: 'number' },
        quality:     { type: 'string', enum: ['Any', 'SD', 'HD-720p', 'HD-1080p', 'Ultra-HD', 'HD - 720p/1080p'] },
        searchNow:   { type: 'boolean' },
        view:        { type: 'string', enum: ['movies', 'queue', 'history'] },
        movieId:     { type: 'number' },
        guid:        { type: 'string' },
        indexerId:   { type: 'number' },
        deleteFiles: { type: 'boolean' },
        limit:       { type: 'number' },
      },
      required: ['action'],
    },
  },

  downloads: {
    name: 'downloads',
    description: "Manage downloads. direct=download from direct HTTP URL or YouTube/video sites ONLY (never for Google Drive, Mega, MediaFire). add=send to PyLoad for file hosters (Google Drive, Mega, MediaFire, etc.). status=check PyLoad queue + download folders. organize=move completed to Jellyfin. delete_pyload=remove PyLoad packages. Sonarr/Radarr/qBit: list_queue, cancel, purge, clean_orphans.",
    parameters: {
      type: 'object',
      properties: {
        action:          { type: 'string', enum: ['direct', 'add', 'status', 'organize', 'delete_pyload', 'cancel', 'purge', 'clean_orphans', 'list_queue'] },
        url:             { type: 'string', description: 'Single URL for direct download (action=direct)' },
        urls:            { type: 'array', items: { type: 'string' } },
        packageName:     { type: 'string', description: 'Descriptive name for PyLoad download (becomes folder name)' },
        packageIds:      { type: 'array', items: { type: 'number' }, description: 'PyLoad package IDs to delete' },
        packageFolder:   { type: 'string', description: 'Download subfolder to organize (from status response)' },
        showName:        { type: 'string', description: 'Target name in Jellyfin' },
        libraryFolder:   { type: 'string', enum: ['tv', 'movies', 'music', 'anime'] },
        seasonNumber:    { type: 'number' },
        episodeNumber:   { type: 'number' },
        archivePassword: { type: 'string', description: 'Password for RAR/ZIP/7z archives' },
        source:          { type: 'string', enum: ['sonarr', 'radarr', 'qbittorrent'] },
        queueIds:        { type: 'array', items: { type: 'number' } },
        torrentHashes:   { type: 'array', items: { type: 'string' } },
        seriesId:        { type: 'number' },
        movieId:         { type: 'number' },
      },
      required: ['action'],
    },
  },

  optimize: {
    name: 'optimize',
    description: 'Optimize media files. analyze=show audio/subtitle tracks. optimize=remove unwanted tracks (specify keepAudioLangs). fix_subs=convert ASS/SSA subtitles to SRT to prevent transcoding.',
    parameters: {
      type: 'object',
      properties: {
        action:        { type: 'string', enum: ['analyze', 'optimize', 'fix_subs'] },
        mediaPath:     { type: 'string', description: "Path to media (relative like 'anime/Show' or absolute like '/data/anime/Show' — both work)" },
        keepAudioLangs:{ type: 'array', items: { type: 'string' }, description: "Audio languages to keep (e.g. ['spa','eng'])" },
        keepSubLangs:  { type: 'array', items: { type: 'string' } },
        removeAllSubs: { type: 'boolean' },
        dryRun:        { type: 'boolean' },
      },
      required: ['action', 'mediaPath'],
    },
  },

  maintenance: {
    name: 'maintenance',
    description: 'Server maintenance. cleanup=clean temp files, orphan downloads, ghost entries. check_jobs=monitor background operations by jobId.',
    parameters: {
      type: 'object',
      properties: {
        action: { type: 'string', enum: ['cleanup', 'check_jobs'] },
        dryRun: { type: 'boolean' },
        jobId:  { type: 'string' },
      },
      required: ['action'],
    },
  },
};

export const TOOL_GROUPS: Record<string, string[]> = {
  series:      ['series'],
  movies:      ['movies'],
  files:       ['library_ops', 'media_query'],
  maintenance: ['optimize', 'maintenance'],
  downloads:   ['downloads'],
  status:      ['server_info', 'media_query'],
};

export const KEYWORD_MAP: Record<string, string[]> = {
  serie: ['series', 'files'],          series: ['series', 'files'],
  anime: ['series', 'files'],          temporada: ['series', 'files'],
  season: ['series', 'files'],         episodio: ['series', 'files'],
  episode: ['series', 'files'],        capitulo: ['series', 'files'],
  pelicula: ['movies', 'files'],       peliculas: ['movies', 'files'],
  movie: ['movies', 'files'],          movies: ['movies', 'files'],
  film: ['movies', 'files'],
  sonarr: ['series', 'downloads'],     radarr: ['movies', 'downloads'],
  qbittorrent: ['downloads'],          qbit: ['downloads'],
  jellyfin: ['status', 'files'],       pyload: ['downloads'],
  descargar: ['series', 'movies', 'downloads'],
  descarga: ['downloads', 'series', 'movies'],
  descargas: ['downloads', 'series', 'movies'],
  download: ['downloads', 'series', 'movies'],
  bajar: ['series', 'movies', 'downloads'],
  borrar: ['files', 'series', 'movies', 'downloads'],
  eliminar: ['files', 'series', 'movies', 'downloads'],
  quitar: ['files', 'series', 'movies', 'downloads'],
  delete: ['files', 'series', 'movies', 'downloads'],
  mover: ['files'],     move: ['files'],
  renombrar: ['files'], rename: ['files'],
  archivo: ['files'],   archivos: ['files'],
  optimizar: ['maintenance'],   optimize: ['maintenance'],
  espacio: ['maintenance', 'status'],
  limpiar: ['maintenance'],     limpieza: ['maintenance'],
  cleanup: ['maintenance'],     subtitulo: ['maintenance'],
  subtitulos: ['maintenance'],  subtitle: ['maintenance'],
  srt: ['maintenance'],         ass: ['maintenance'],
  tracks: ['maintenance'],      audio: ['maintenance'],
  estado: ['status', 'downloads'],
  status: ['status', 'downloads'],
  servidor: ['status', 'maintenance'],
  server: ['status', 'maintenance'],
  disco: ['status'],    disk: ['status'],
  usuarios: ['status'],
  cola: ['downloads', 'series', 'movies'],
  queue: ['downloads', 'series', 'movies'],
  torrent: ['downloads'],   torrents: ['downloads'],
  mega: ['downloads'],      mediafire: ['downloads'],
  listar: ['files', 'status'],  lista: ['files', 'status'],
  buscar: ['series', 'movies', 'files'],
  search: ['series', 'movies', 'files'],
  tengo: ['status', 'files'],   hay: ['status', 'files'],
  contenido: ['status', 'files'],
  biblioteca: ['status', 'files'],
  library: ['status', 'files'],
  job: ['maintenance'],         jobs: ['maintenance'],
  progreso: ['maintenance', 'downloads'],
  progress: ['maintenance', 'downloads'],
};
