import type { WizardAnswers } from "../types.js";

interface ServiceRoute {
  subdomain: string;
  target: string;
}

/**
 * Generate a Caddyfile for reverse-proxying all Mediabox services
 * with automatic HTTPS via Let's Encrypt.
 */
export function generateCaddyfile(answers: WizardAnswers): string {
  const domain = answers.baseDomain!;
  const email = answers.letsEncryptEmail!;

  const routes: ServiceRoute[] = [
    { subdomain: "jellyfin", target: "jellyfin:8096" },
    { subdomain: "sonarr", target: "sonarr:8989" },
    { subdomain: "radarr", target: "radarr:7878" },
    { subdomain: "prowlarr", target: "prowlarr:9696" },
    { subdomain: "qbit", target: "qbittorrent:8085" },
    { subdomain: "pyload", target: "pyload:8000" },
  ];

  if (answers.enableBazarr) {
    routes.push({ subdomain: "bazarr", target: "bazarr:6767" });
  }

  const blocks = routes.map(
    (r) =>
      `${r.subdomain}.${domain} {\n  reverse_proxy ${r.target}\n}`
  );

  // MCP server at the root domain
  blocks.unshift(`${domain} {\n  reverse_proxy mcp-server:3000\n}`);

  const lines = [
    "# =============================================================================",
    "# Mediabox MCP — Caddyfile",
    "# Generated by create-mediabox CLI",
    "# Automatic HTTPS via Let's Encrypt",
    "# =============================================================================",
    "",
    "{",
    `  email ${email}`,
    "}",
    "",
    ...blocks,
    "",
  ];

  return lines.join("\n");
}
