import type { WizardAnswers, DiscoveredKeys } from "../types.js";

/**
 * Generate the .env file content from wizard answers.
 * API keys that are discovered in Phase 4 are left empty initially.
 */
export function generateEnv(answers: WizardAnswers, keys?: Partial<DiscoveredKeys>): string {
  const lines: string[] = [
    "# =============================================================================",
    "# Mediabox MCP — Environment Configuration",
    "# Generated by create-mediabox CLI",
    "# =============================================================================",
    "",
    `TZ=${answers.timezone}`,
    "",
    "# Service API Keys (auto-populated by setup wizard)",
    `JELLYFIN_API_KEY=${keys?.jellyfinApiKey ?? ""}`,
    `SONARR_API_KEY=${keys?.sonarrApiKey ?? ""}`,
    `RADARR_API_KEY=${keys?.radarrApiKey ?? ""}`,
    `QBIT_PASSWORD=${answers.qbitPassword}`,
    `PYLOAD_USER=pyload`,
    `PYLOAD_PASSWORD=pyload`,
    "",
    "# MCP Server",
    `MCP_PUBLIC_URL=${answers.mcpPublicUrl}`,
    `MCP_AUTH_SECRET=${answers.mcpAuthSecret}`,
    `INTERNAL_API_KEY=${answers.internalApiKey}`,
  ];

  if (answers.enableTelegram) {
    lines.push(
      "",
      "# Telegram Bot",
      `TELEGRAM_BOT_TOKEN=${answers.telegramBotToken ?? ""}`,
      `LLM_PROVIDER=${answers.llmProvider ?? "openrouter"}`,
    );
    if (answers.llmProvider === "openrouter") {
      lines.push(
        `OPENROUTER_API_KEY=${answers.llmApiKey ?? ""}`,
        `LLM_MODEL=${answers.llmModel ?? "openai/gpt-4o"}`,
      );
    } else if (answers.llmProvider === "google") {
      lines.push(`GOOGLE_AI_API_KEY=${answers.llmApiKey ?? ""}`);
    }
    lines.push(`ALLOWED_TELEGRAM_USERS=${answers.allowedTelegramUsers ?? ""}`);
  }

  lines.push(""); // trailing newline
  return lines.join("\n");
}

/**
 * Update specific keys in an existing .env file content.
 */
export function updateEnvKeys(envContent: string, updates: Record<string, string>): string {
  let result = envContent;
  for (const [key, value] of Object.entries(updates)) {
    const regex = new RegExp(`^${key}=.*$`, "m");
    if (regex.test(result)) {
      result = result.replace(regex, `${key}=${value}`);
    } else {
      result += `\n${key}=${value}`;
    }
  }
  return result;
}
